name: CI
on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
concurrency:
  group: "ci"
  cancel-in-progress: true
jobs:
  web:
    name: Web
    uses: ./.github/workflows/web.yml
  license-check:
    name: License Check
    uses: ./.github/workflows/license_check.yml
