name: CI
on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main]
concurrency:
  group: "ci"
  cancel-in-progress: true
jobs:
  web:
    name: Web
    uses: ./.github/workflows/web.yml
  license-check:
    name: License Check
    uses: ./.github/workflows/license_check.yml
  build:
    name: Build (${{ matrix.name }})
    runs-on: ${{ matrix.runs_on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS x64
            runs_on: macos-13
          - name: Linux x64
            runs_on: ubuntu-24.04
          - name: Linux ARM64
            runs_on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y --no-install-recommends \
            libspdlog-dev \
            ninja-build \
            pkg-config \
            zlib1g-dev \
            librealsense2-dev \
            librealsense2-utils \
          && sudo apt-get autoremove -y && sudo apt-get clean -y

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install spdlog ninja readline zlib

      - name: Build pan_tilt_demo
        working-directory: pan_tilt_demo
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./build.sh -G Ninja
